# Generated by Django 2.0.4 on 2018-05-07 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_username', models.CharField(default='', max_length=255, unique=True)),
                ('user_password', models.CharField(default='', max_length=20)),
                ('user_email', models.EmailField(default='', max_length=255)),
                ('user_mobile', models.CharField(default='', max_length=255)),
                ('user_gender', models.CharField(default='', max_length=20)),
                ('user_dob', models.CharField(default='', max_length=255)),
                ('user_image', models.CharField(max_length=255, null=True)),
                ('user_isactive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_roleid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='patient.UserRole'),
        ),
    ]
