# Generated by Django 2.0.4 on 2018-05-07 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='myuser',
        ),
    ]
