# Generated by Django 2.0.4 on 2018-05-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20180507_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_email',
            field=models.EmailField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
