# Generated by Django 2.0.4 on 2018-05-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20180507_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_email',
            field=models.EmailField(default='', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
