# Generated by Django 2.0.4 on 2018-05-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_username', models.CharField(default='', max_length=255)),
                ('staff_password', models.CharField(default='', max_length=20)),
                ('staff_email', models.EmailField(default='', max_length=255, unique=True)),
                ('staff_mobile', models.CharField(default='', max_length=255)),
                ('staff_gender', models.CharField(default='', max_length=20)),
                ('staff_dob', models.CharField(default='', max_length=255)),
                ('staff_image', models.CharField(max_length=255, null=True)),
                ('staff_isactive', models.BooleanField(default=True)),
            ],
        ),
    ]
