# Generated by Django 2.0.4 on 2018-05-20 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20180507_1313'),
        ('manager', '0002_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_roleid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='patient.UserRole'),
        ),
    ]
